GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO crowdsourcing;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO crowdsourcing;
GRANT USAGE, CREATE ON SCHEMA public TO crowdsourcing;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO crowdsourcing;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO crowdsourcing;

