window.AppState = function () {
  return {
    page: 'home',
    user: null,
    role: null,
    toast: { show: false, type: 'info', text: '' },
    acceptPdn: false,

    loginForm: { email: '', password: '' },
    registerForm: { first_name: '', last_name: '', email: '', password: '' },

    projects: [],
    myProjects: [],
    projectFilter: '',
    projectSearch: '',
    projectCategoryFilter: '',
    projectSort: 'new',
    categories: [],
    selectedProject: null,
    projectTab: 'about',
    canManage: false,
    canLead: false,
    isMember: false,
    myParticipationRequest: null,

    projectDraft: { id: null, title: '', short_description: '', full_description: '', category_ids: [], tags: [], goal_description: '', planned_end_date: '', image_url: '' },
    projectTagInput: '',
    themeSearch: '',
    skillSearch: '',
    showProjectForm: false,
    showParticipateForm: false,
    participateDraft: { comment: '', resume_url: '' },
    tagCatalog: [],
    taskAssignees: [],

    tasks: [],
    taskView: 'kanban',
    taskDraft: { id: null, title: '', description: '', priority: 'средний', difficulty: 3, due_date: '', attachment_url: '' },
    showTaskForm: false,
    selectedTask: null,
    taskComments: [],
    newComment: '',
    rateDraft: 0,
    participants: [],
    requests: [],

    chats: [],
    selectedChat: null,
    messages: [],
    newMessage: '',
    ws: null,
    chatProjects: [],
    activeChatProject: null,

    editingProfile: false,
    profileDraft: { first_name: '', last_name: '', password: '', group_id: '' },
    showOrganizerForm: false,
    showTeacherForm: false,
    organizerDraft: { experience_description: '', resume_url: '' },
    teacherDraft: { experience_description: '', resume_url: '' },
    myOrganizerRequest: null,
    myTeacherRequest: null,
    groups: [],

    invitations: [],
    invitationsCount: 0,
    showInviteForm: false,
    inviteDraft: { mode: 'email', emails: [], emailInput: '', group_ids: [], groupSearch: '', message: '' },
    projectInvitations: [],

    adminTab: 'dashboard',
    adminUsers: [],
    adminRequests: [],
    adminRequestFilter: 'all',
    adminProjects: [],
    adminProjectFilter: '',
    adminUserSearch: '',
    adminUserPage: 1,
    adminProjectPage: 1,
    summary: null,
    dashboard: null,
    kpiData: null,
    kpiUsers: [],
    kpiProjects: [],
    reportFrom: '',
    reportTo: '',
    reportGroupID: '',
    reportUserType: '',
    kpiGroups: [],
    kpiUserTypes: [],
    charts: {},
    showUserForm: false,
    userDraft: { id: null, first_name: '', last_name: '', email: '', password: '', status: true, is_participant: true, is_organizer: false, is_admin: false, user_type: 'student', group_id: '' },

    dictTab: 'categories',
    dictCategories: [],
    dictTags: [],
    dictGroups: [],
    dictSearch: '',
    dictPage: 1,
    dictDraft: { id: null, name: '' },
    showDictForm: false,
    adminRequestTypeFilter: 'all',

    recommended: [],
    goals: [],
    goalDraft: { title: '', description: '' },
    showGoalForm: false,
    requiredSkills: [],
    requiredSkillSearch: '',

    projectDashboard: null,
    projectAnalyticsFrom: '',
    projectAnalyticsTo: '',

    mySkills: [],
    myInterests: [],
    skillInput: '',
  };
};
